### ISSUE TITLE
Server crash with Titanium and Functional Storage [1.18.1]

### ISSUE THREAD

**Issue by lays24mc** [InnovativeOnlineIndustries/Titanium#105]
Hi,

my server crash when I use the mod titanium and functional storage for 1.18.1. Did I need some other mod? Or is this a mod issue. Here the crashlog: https://pastebin.com/DhTme7PW 

I use Forge 39.0.8 and the newest version of titanium and functional storage

**Comment by lays24mc** [comment]
Fixed in titanium-1.18-3.4.0-25.jar or a later version? :D

**Comment by Buuz135** [comment]
It should be fixed in 3.4.0-25

**Comment by lays24mc** [comment]
Hmm okay, thats strange. My Server crashed now with this: https://pastebin.com/ruqMJ57M

**Comment by Buuz135** [comment]
I will fix it in FS

**Comment by Buuz135** [comment]
Everything should be out and fixed, you should update titanium again

**Comment by lays24mc** [comment]
It works now. Thank you :)
