### ISSUE TITLE
[1.18] SushiGoCrafting/Titanium server crash on new Titanium update.

### ISSUE THREAD

**Issue by ShibeTemple** [InnovativeOnlineIndustries/Titanium#111]
**Titanium Version: ** titanium-1.18.2-3.5.5-37.jar

**Crashlog If Applicable (Upload to pastebin/gist): **

With the new Titanium update, SushiGoCrafting/Titanium crashes when a user joins a dedicated server.

Server log: https://gist.github.com/ShibeTemple/303f860dfc4f35abbb0cdd279dc0b8fb

**Comment by Buuz135** [comment]
Fixed https://github.com/Buuz135/SushiGoCrafting/commit/5fda0dc79851867fdf4670c337787b54aca4e4b3
