### ISSUE TITLE
1.14.4 crash on newer forge version

### ISSUE THREAD

**Issue by Sunekaer** [InnovativeOnlineIndustries/Titanium#2]
https://paste.dimdev.org/babibazuju.sql
forge-28.0.95
titanium-2.1.58

**Comment by raziel23x** [comment]
Running versions
Portality-1.14.4-2.0.14
titanium-2.1.58

![image](https://user-images.githubusercontent.com/441966/64491303-2b1e0c80-d235-11e9-8176-71f582481863.png)
[latest.log](https://github.com/InnovativeOnlineIndustries/Titanium/files/3587785/latest.log)

**Comment by Buuz135** [comment]
https://www.curseforge.com/minecraft/mc-mods/titanium/files/2783104
