### ISSUE TITLE
[1.15.1] Forge breaks your mod.

### ISSUE THREAD

**Issue by Cr4fTJuNkiE** [InnovativeOnlineIndustries/Titanium#32]
**Titanium Version: **
titanium-1.15.1-2.3.4

Forge 1.15.1 - 20.0.51 
Changlog "Renamed ModConfigEvent.ConfigReloading to ModConfigEvent.Reloading"

The change breaks your mod. Please update. Thanks.

**Comment by OpponentBacon73** [comment]
I have this Issue too.

**Comment by SkySom** [comment]
This is fixed in current versions
