### ISSUE TITLE
1.15.2 Exception in server tick loop

### ISSUE THREAD

**Issue by Pelargir42** [InnovativeOnlineIndustries/Titanium#39]
**Titanium Version: **
titanium-1.15.2-2.3.6

**Crashlog If Applicable (Upload to pastebin/gist): **
https://pastebin.com/S6zGEXpd

funny thing is it was working for several days before I saw this error.  

only happens on dedicated server, not on client.

**Comment by Buuz135** [comment]
Delete your config file
