### ISSUE TITLE
1.15.2 errors in logs

### ISSUE THREAD

**Issue by eloe79** [InnovativeOnlineIndustries/Titanium#47]
[latest.log](https://github.com/InnovativeOnlineIndustries/Titanium/files/4416801/latest.log)
[crash-2020-04-01_19.21.35-client.txt](https://github.com/InnovativeOnlineIndustries/Titanium/files/4416802/crash-2020-04-01_19.21.35-client.txt)

**Titanium Version: **
titanium-1.15.2-2.3.7.jar
**Crashlog If Applicable (Upload to pastebin/gist): **

**Comment by SkySom** [comment]
Didn't use proper issue reporting, and also Titanium isn't mentioned in that crash log.
