### ISSUE TITLE
[1.15] [17Apr2020 16:41:35.246] [Server thread/ERROR] [net.minecraft.item.crafting.RecipeManager/]

### ISSUE THREAD

**Issue by BedrockLegends** [InnovativeOnlineIndustries/Titanium#50]
**Titanium Version: ** 1.15.2  2.3.7

**Crashlog If Applicable (Upload to pastebin/gist): **
https://gist.github.com/BedrockLegends/3003a040b75df6c19c4e5e61bde5f40e

**Comment by Lanse505** [comment]
Known issue, corrected in dev.
