### ISSUE TITLE
[1.14] Slot 0 not in valid range

### ISSUE THREAD

**Issue by belathus** [InnovativeOnlineIndustries/Titanium#51]
**Titanium Version: ** 2.2.10

**Crashlog If Applicable (Upload to pastebin/gist): ** https://gist.github.com/belathus/509a2a6ddc8e3d4b3a0a5d7527877bf3

This is the second such crash we've had on my server. Since I didn't build the latex processing unit, I'm not sure about the details.

**Comment by Buuz135** [comment]
Update to 1.15, 1.14 is not longer supported
