### ISSUE TITLE
[1.15.2] Pitiful fuel generator crash

### ISSUE THREAD

**Issue by veryslowinthehead** [InnovativeOnlineIndustries/Titanium#52]
Titanium Version: 1.15.2 2.3.7

https://pastebin.com/DiSb6btA

as far as i know this is the full log- 
https://gist.github.com/veryslowinthehead/9f4e4aca019c96e5270b665ecd797e32

I was told the progress bar was trying to divide by zero

**Comment by veryslowinthehead** [comment]
👁️👃👁️
     👄

**Comment by Vaelzan** [comment]
For reference, it's this line that is causing the crash. https://github.com/InnovativeOnlineIndustries/Titanium/blob/75e3847594fb481188217fd18f7852dce91967c0/src/main/java/com/hrznstudio/titanium/component/progress/ProgressBarComponent.java#L435
