### ISSUE TITLE
[1.16] Failed to load correctly on the newest Forge version

### ISSUE THREAD

**Issue by Kroko1337** [InnovativeOnlineIndustries/Titanium#71]
**Titanium Version: 3.0.2**

https://pastebin.com/SFZJVzPg

**Comment by realTIMematrix** [comment]
Can confirm this

**Comment by LuckyStrikeOriginal** [comment]
![Screenshot_29](https://user-images.githubusercontent.com/35672513/89097891-c4c15000-d3eb-11ea-9170-5f8d5d94a1c5.png)

Yep

**Comment by Buuz135** [comment]
Fixed in https://github.com/InnovativeOnlineIndustries/Titanium/commit/c2908129d021f49f7bfbd00784dca72c9f143a54
