### ISSUE TITLE
[1.16] CTD from block from Industrial Foregoing ?

### ISSUE THREAD

**Issue by IchigoGames** [InnovativeOnlineIndustries/Titanium#82]
**Titanium Version: **
Minecraft 1.16.5
Forge 36.0.10
titanium-1.16.5-3.2.6
industrial-foregoing-1.16.5-3.2.9-2215ef4

https://pastebin.com/Y83ckLnj not sure what machine is doing it. crash report

if this is a industrial-foregoing issue just let me know and ill report it there but the crash report seem to be Titanium  Related

**Comment by Buuz135** [comment]
Update titanium

**Comment by IchigoGames** [comment]
ok
