### ISSUE TITLE
[1.16] Industrial Foregoing Bioreactor and Mekanism Logistcal Sorter

### ISSUE THREAD

**Issue by LuckyTeran** [InnovativeOnlineIndustries/Titanium#84]
When i lock the inventory (so only certain Items of a kind can be inserted) of an Industrial Foregoing Bioreactor and try to insert items with a Mekanism Logistical Sorter my server crashes (doesn't matter if internal oder dedicaded). Should i send a bug report to Mekanism also?. Here is the crashlog:

[Crashlog](https://pastebin.com/GrKC1ykb)

**Comment by ThatPreston** [comment]
I had the exact same issue. Locked it by accident and it caused a ticking block entity on my server that I am struggling to resolve. When locked setInputFilter is called with (stack, integer) -> !this.filter[integer].isEmpty() && this.filter[integer].isItemEqual(stack) and somehow this is causing an ArrayIndexOutOfBoundsException. (In my log the integer is 9 for some reason.)
[crash-2021-02-26_16.48.16-server.txt](https://github.com/InnovativeOnlineIndustries/Titanium/files/6051430/crash-2021-02-26_16.48.16-server.txt)
