### ISSUE TITLE
[1.16] Titanium failed to load correctly due to "Not enough data available"

### ISSUE THREAD

**Issue by SeaCrusher27** [InnovativeOnlineIndustries/Titanium#88]
**Titanium Version: 1.16.5-3.2.8.2**

**Crashlog If Applicable (Upload to pastebin/gist): https://pastebin.com/ULS3u8Vg**

Has worked fine until this morning, the only thing i did was update forge on the server if that helps

**Comment by Buuz135** [comment]
Delete the Titanium config files
